name: Rust Nightly

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt, clippy
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Catch common mistakes
      run: cargo clippy --all-features --all-targets -- -D warnings
